defaults_development: &defaults_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 10

development:
  database: drophunter_web_dev
  <<: *defaults_development

production:
  database: drophunter_web_dev
  <<: *defaults_development

test:
  database: content_checker_test
  <<: *defaults_development
