# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1769ada33e9b51eedddcaae60dca48881a081f05a7ac02f0d6557b1927fc5f91018e8c39b1dae0c86332c150eecbdea7f7791c8d7adb015c0d313431403843b

test:
  secret_key_base: ac4c46508208ec8cce6b18d00259443a6e707a84f0740e26ab75652a186994a2af8aa8903869aed5f7b48f8e44c3f16a785988e24ef675c03470f72901a63796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
